//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Аккредитационные_показатели
{
    using System;
    using System.Collections.Generic;
    
    public partial class As_teacher_pract
    {
        public int Code_as { get; set; }
        public int Code_teacher { get; set; }
        public int Code_practitioner { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        public virtual Practitioners Practitioners { get; set; }
    }
}
