//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Аккредитационные_показатели
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disciplines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Disciplines()
        {
            this.AcademicLoad = new HashSet<AcademicLoad>();
        }
    
        public int Code_discipline { get; set; }
        public int Code_adst { get; set; }
        public string Title_discipline { get; set; }
        public string HoursLectures_discipline { get; set; }
        public string HoursPractice_discipline { get; set; }
        public string HoursCredits_discipline { get; set; }
        public string HoursExam_discipline { get; set; }
        public string HoursConsultation_discipline { get; set; }
        public string HoursCoursework_discipline { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcademicLoad> AcademicLoad { get; set; }
        public virtual Admission_student Admission_student { get; set; }
    }
}
