//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Аккредитационные_показатели
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practitioners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Practitioners()
        {
            this.As_teacher_pract = new HashSet<As_teacher_pract>();
        }
    
        public int Code_practitioner { get; set; }
        public string FIO_practitioner { get; set; }
        public string TitleOrg_practitioner { get; set; }
        public string Position_practitioner { get; set; }
        public string PeriodOperation_practitioner { get; set; }
        public string WorkExperience_practitioner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<As_teacher_pract> As_teacher_pract { get; set; }
    }
}
